default_output: "discord"  # 今回はDiscordのみ
webhook_file: "config/webhooks.env"
category_to_output:
  travel: "discord"
  news:   "discord"
category_to_env:
  ai_jp:   "DISCORD_WEBHOOK_AI_JP"
  camera_en: "DISCORD_WEBHOOK_CAMERA_EN"
  camera_jp: "DISCORD_WEBHOOK_CAMERA_JP"
  camera_official: "DISCORD_WEBHOOK_CAMERA_OFFICIAL"
  english: "DISCORD_WEBHOOK_ENGLISH"
  entertainment_en: "DISCORD_WEBHOOK_ENTERTAINMENT_EN"
  entertainment_jp: "DISCORD_WEBHOOK_ENTERTAINMENT_JP"
  gadget_en: "DISCORD_WEBHOOK_GADGET_EN"
  gadget_jp: "DISCORD_WEBHOOK_GADGET_JP"
  money:   "DISCORD_WEBHOOK_MONEY"
  news_en:   "DISCORD_WEBHOOK_NEWS_EN"
  news_jp:   "DISCORD_WEBHOOK_NEWS_JP"
  productivity_en:   "DISCORD_WEBHOOK_PRODUCTIVITY_EN"
  productivity_jp:   "DISCORD_WEBHOOK_PRODUCTIVITY_JP"
  tech_jp: "DISCORD_WEBHOOK_TECH_JP"  
  travel_jp: "DISCORD_WEBHOOK_TRAVEL_JP"  
youtube:
  api_key_file: "config/youtube.env"
  api_key_name: "YOUTUBE_API_KEY"
rate_limit:
  fetch_sleep_ms: 1200
  post_sleep_ms: 900
filters:
  include_premieres: false
  include_live: false
  include_shorts: true
timezone: "Asia/Tokyo"
