default_output: "discord"  # 今回はDiscordのみ
category_to_output:
  travel: "discord"
  news:   "discord"
category_to_env:
  travel: "https://discord.com/api/webhooks/1434205204831535185/X-x7ZYVHfSi1Ux8XTNFdmegc-JNtT6w3lY4-kAxDls_EEJIH1py4f8NnXgQu2Or3_3kk"  # 実値は環境変数/Secretsで注入
  news:   "DISCORD_WEBHOOK_NEWS"
rate_limit:
  fetch_sleep_ms: 1200
  post_sleep_ms: 900
filters:
  include_premieres: false
  include_live: false
  include_shorts: true
timezone: "Asia/Tokyo"
